export const ONE_ENTRY_FILENAME: string = "one-entry"
export const ONE_FALSE_ENTRY_FILENAME: string = "one-false-entry"
export const EMPTY_FILENAME: string = "empty"
export const TWO_ENTRIES_FILENAME: string = "two-entries"
export const TWO_ENTRIES_WITH_ONE_FALSE_FILENAME: string = "two-entries-with-one-false"
export const MULTIPLE_ENTRIES_FILENAME: string = "multiple-entries"

const ENTRY_FILES_REPOSITORY: string = `_entries-files`
const FILE_EXTENSION: string = ".txt"

export const ONE_ENTRY_PATH: string = `${ENTRY_FILES_REPOSITORY}/${ONE_ENTRY_FILENAME}${FILE_EXTENSION}`
export const ONE_FALSE_ENTRY_PATH: string = `${ENTRY_FILES_REPOSITORY}/${ONE_FALSE_ENTRY_FILENAME}${FILE_EXTENSION}`
export const EMPTY_PATH: string = `${ENTRY_FILES_REPOSITORY}/${EMPTY_FILENAME}${FILE_EXTENSION}`
export const TWO_ENTRIES_PATH: string = `${ENTRY_FILES_REPOSITORY}/${TWO_ENTRIES_FILENAME}${FILE_EXTENSION}`
export const TWO_ENTRIES_WITH_ONE_FALSE_PATH: string = `${ENTRY_FILES_REPOSITORY}/${TWO_ENTRIES_WITH_ONE_FALSE_FILENAME}${FILE_EXTENSION}`
export const MULTIPLE_ENTRIES_PATH: string = `${ENTRY_FILES_REPOSITORY}/${MULTIPLE_ENTRIES_FILENAME}${FILE_EXTENSION}`

const GENERATED_FILES_US4_REPOSITORY: string = `_generated-files-US4`
const RESULT_SUFFIX: string = "-result"

export const ONE_ENTRY_PATH_RESULT: string = `${GENERATED_FILES_US4_REPOSITORY}/${ONE_ENTRY_FILENAME}${RESULT_SUFFIX}${FILE_EXTENSION}`
export const ONE_FALSE_ENTRY_PATH_RESULT: string = `${GENERATED_FILES_US4_REPOSITORY}/${ONE_FALSE_ENTRY_FILENAME}${RESULT_SUFFIX}${FILE_EXTENSION}`
export const EMPTY_PATH_RESULT: string = `${GENERATED_FILES_US4_REPOSITORY}/${EMPTY_FILENAME}${RESULT_SUFFIX}${FILE_EXTENSION}`
export const TWO_ENTRIES_PATH_RESULT: string = `${GENERATED_FILES_US4_REPOSITORY}/${TWO_ENTRIES_FILENAME}${RESULT_SUFFIX}${FILE_EXTENSION}`
export const TWO_ENTRIES_WITH_ONE_FALSE_PATH_RESULT: string = `${GENERATED_FILES_US4_REPOSITORY}/${TWO_ENTRIES_WITH_ONE_FALSE_FILENAME}${RESULT_SUFFIX}${FILE_EXTENSION}`
export const MULTIPLE_ENTRIES_PATH_RESULT: string = `${GENERATED_FILES_US4_REPOSITORY}/${MULTIPLE_ENTRIES_FILENAME}${RESULT_SUFFIX}${FILE_EXTENSION}`

const GENERATED_FILES_US5_REPOSITORY: string = `_generated-files-US5`
export const AUTHORIZED_PATH_RESULT: string = `${GENERATED_FILES_US5_REPOSITORY}/authorized${RESULT_SUFFIX}${FILE_EXTENSION}`
export const ERRORED_PATH_RESULT: string = `${GENERATED_FILES_US5_REPOSITORY}/errored${RESULT_SUFFIX}${FILE_EXTENSION}`
export const UNKNOWN_PATH_RESULT: string = `${GENERATED_FILES_US5_REPOSITORY}/unknown${RESULT_SUFFIX}${FILE_EXTENSION}`

export const ONE_ENTRY_CONTENT: string[] = ["123456789"]
export const ONE_FALSE_ENTRY_CONTENT: string[] = ["123?5678?"]
export const EMPTY_CONTENT: string[] = [""]
export const TWO_ENTRIES_CONTENT: string[] = ["123456789", "123456709"]
export const TWO_ENTRIES_WITH_ONE_FALSE_CONTENT: string[] = ["123456789", "1234?6709"]
export const MULTIPLE_ENTRIES_CONTENT: string[] = ["123456789", "123456709", "1?34567?9", "12?13678?", "356609701", "457508000"]
